### ISSUE TITLE
Incompatible with Character Select mod

### ISSUE THREAD

**Issue by MainMemory** [SonicFreak94/sadx-dc-lighting#16]
The game crashes on the character select screen if this mod and the Character Select mod are enabled together. Could actually be an issue with the Character Select mod.

**Comment by SonicFreak94** [comment]
It's a mix of both.

I use a trampoline to hook the function [here](https://github.com/SonicFreak94/sadx-dc-lighting/blob/master/sadx-dc-lighting/mod.cpp#L358), but SADXCharSel [uses a jump](https://github.com/MainMemory/SADXCharSel/blob/81b8a200389bf0e564cbd31eae5471bd671612b6/SADXCharSel/SADXCharSel.cpp#L1205) offset from the start of the function.

Two solutions that come to mind:
* Detect the jump at that offset and fix it, since my trampoline copies that range
* Use a trampoline in SADXCharSel

**Comment by SonicFreak94** [comment]
https://github.com/MainMemory/SADXCharSel/pull/1
