### ISSUE TITLE
Chao Garden issues

### ISSUE THREAD

**Issue by BlueSpikeball** [SonicFreak94/sadx-dc-lighting#17]
The doors in the Station Square Chao Garden have a really light tone, making them look bizarre. Here are comparison shots:
http://imgur.com/a/NsEwe

I've also noticed that the lighting looks overly dark, even compared with the Dreamcast version. This is also true of Station Square in general, but it's the darkest at its Chao Garden.

Another thing is that Black Market eggs look white in the preview box thingy:
http://imgur.com/a/fOUOk

**Comment by SonicFreak94** [comment]
The doors are objects whose materials need to be located in order to fix the full-bright crap they've got going on. As for the Black Market things, I have a hunch that it's related to issue #4, but it's strange that they would use basic models for those, but chunk models for everything else (see #3).

Thanks for the report.

**Comment by SonicFreak94** [comment]
75214cabc8ebb2ca6441c864a60be81b4adbf099 addressed the overall brightness issue, so the objects in question should at least look a little less out of place. I still intend to implement a proper fix, though.

**Comment by SonicFreak94** [comment]
I'm considering this fixed now that the materials have been dealt with. The items in the black market are probably related to texture palletization which I need to implement support for.
