### ISSUE TITLE
Sonic's Character Model visible polygons

### ISSUE THREAD

**Issue by Sonikko** [SonicFreak94/sadx-dc-lighting#25]
I noticed this imperfection various times, I'm pretty sure it happens in Emerald Coast and Windy Valley too, or every time the camera gets closer anyway.
Zoom the picture to see it, it's not easy to notice.
![screenshot 2017-01-05 23 03 402](https://cloud.githubusercontent.com/assets/24740235/21700456/d9753b6e-d3a0-11e6-818f-f65a0db7941e.png)
![screenshot 2017-01-05 23 03 40](https://cloud.githubusercontent.com/assets/24740235/21700455/d973836e-d3a0-11e6-9d12-d515587c92b5.png)

**Comment by SonicFreak94** [comment]
Hmm, this is a strange one. It appears to be on the seams of the base texture. Since the palette textures are used as vertex colors, it seems unlikely that the (unfiltered) palette texture could be causing that kind of artifact. The question is then: what am I doing in the shader that's causing it to break the base texture?

Strange indeed. Thanks for the report; I'll see what I can do.

**Comment by SonicFreak94** [comment]
This appears to be an issue with vanilla SADX; it could just be that the palette lighting makes it more noticeable. I imagine it's a precision issue in the conversion from the original integer UV coordinates to standard Direct3D floating point UV coordinates.
