### ISSUE TITLE
Wave effect in Emerald Coast

### ISSUE THREAD

**Issue by PiKeyAr** [SonicFreak94/sadx-dc-lighting#29]
I don't know how doable this is, but it's a really cool effect that added a lot to the atmosphere in the original game. 
https://youtu.be/DjUgfunJu84?t=268
The lighting on the water changes to simulate a wave. Shame it got cut like everything else in SADX, really.
I hope something can be done to recreate or at least simulate it in some way.

**Comment by SonicFreak94** [comment]
While not strictly lighting related, it would probably be easier to implement in a shader than in the fixed function pipeline.

The Dreamcast clearly switches to a higher poly count mesh during the effect (or dynamically subdivides), so that would need to be re-implemented. That of course means understanding the entity's existing code in SADX, which ought to be "fun".

**Comment by PiKeyAr** [comment]
Since the wave effect is going to be implemented in the DC mod soon and no lighting tweaks seem necessary, I think this can be closed now.
