### ISSUE TITLE
Minor graphical issue in Station Square

### ISSUE THREAD

**Issue by BlueSpikeball** [SonicFreak94/sadx-dc-lighting#39]
Similarly to the previous problem with the SS Chao Garden doors (thanks for fixing it, btw), the doors to the hotel look too bright with this mod:

https://imgur.com/a/XbiiR

**Comment by PiKeyAr** [comment]
This happens without the mod as well. There's a function in SADX that is supposed to turn on the lights when you're inside the hotel, but it's kinda dumb and broken, so it forces the door to always ignore lighting. It's fixed in Dreamcast Conversion, but if you want to fix it yourself, you need to nop the code at 0x00630AE0.

**Comment by SonicFreak94** [comment]
Yeah, that's a vanilla SADX thing. Might be cool to make a custom palette for inside though.
